### PR TITLE
Scripts update for openssl dependency removal

### PR DESCRIPTION
**Pull request by wmathurin**
If you want the plugin (with new binaries etc) for unstable check out: https://github.com/wmathurin/SalesforceMobileSDK-CordovaPlugin/tree/unstable_all_updates

If building a app, do: cordova plugin add https://github.com/wmathurin/SalesforceMobileSDK-CordovaPlugin#unstable_all_updates

### CODE REVIEW

**Comment by bhariharan** [comment]
Looks good. Shouldn't this go against the ```unstable``` branch?

**Comment by wmathurin** [comment]
On my fork for the plugin, i have two unstable branches with explicit names as to what they are (unstable_script_updates and unstable_all_updates), I thought we could do the same on the forcedotcom repo?

**Comment by bhariharan** [comment]
I suppose we could, but do we need the demarcation, or can we make do with one? I'm okay either way.

**Comment by wmathurin** [comment]
On all the other repo the unstable branches are usable but this only has config/scripts changes so would most likely break. (That being said, I doubt anybody is trying to use it)

**Comment by wmathurin** [comment]
(Next pull request iOS-Package)

**Comment by bhariharan** [comment]
But we'll need to merge both those branches to ```unstable``` eventually, before release?

**Comment by wmathurin** [comment]
We don't want the history of binaries commits so instead of merging the
branch with binaries we would just rerun the tools/update.sh script the day
of the release.

**Comment by bhariharan** [comment]
Right. I think it's okay for ```unstable``` to have only script updates and be broken.

**Comment by wmathurin** [comment]
Ok I'll rename the target branch

**Pull request closed without merging**
