### PR TITLE
Cordova update script and plugin updates

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by wmathurin** [comment]
We need to fix the copy_and_fix method.
Line 53 is only fixing import statement that have <Salesforce.../....h> so won't match SmartStore and SmartSync imports.

**Comment by bhariharan** [comment]
@wmathurin Like [this](https://github.com/bhariharan/SalesforceMobileSDK-CordovaPlugin/commit/c6be3333c3f4b4147e3edc4eebc30b2efdefacea)?

**Comment by wmathurin** [comment]
The second sed will overwrite whatever the first one did.
I think that should work:
```shell
find tmp -name $1 | xargs sed 's/\#import\ \<Salesforce.*\/\(.*\)\>/#import "\1"/' | sed 's/\#import\ \<SmartStore.*\/\(.*\)\>/#import "\1"/' > src/ios/$2/$1
```

The two sed commands should be mergeable into one using \(Salesforce\|Smartstore\) but I can't get that to work (may be OS X sed doesnt' support \|)

**Comment by khawkins** [comment]
Perhaps try `sed -E`?  More robust regex support with the -E option.

**Comment by wmathurin** [comment]
Indeed the following seems to do the job as well:
```shell
find tmp -name $1 | xargs sed -E 's/#import <(Salesforce|SmartStore).*\/(.*)>/#import "\2"/' > src/ios/$2/$1
```

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/bhariharan/SalesforceMobileSDK-CordovaPlugin/commit/e6ac7941a1d6f394a343dc58e8fd80187e69e345).

**Pull request merged**
