### PR TITLE
Tries to address all problems discussed on issue #157

### PR DESCRIPTION
**Pull request by coderReview**
Related to issue #157

### CODE REVIEW

**Comment by bhariharan** [comment]
Thanks @coderReview! I'll run some tests locally and get this merged.

**Comment by JavierAbrego** [comment]
I have tried to...
cordova create test
npm install shelljs
cordova plugin add C:\SalesforceMobileSDK-CordovaPlugin-unstable
cordova platform add android@5.0.0
cordova prepare

Now opening the project in Android gives the following error message
Error:(5, 0) Project with path ':libs:SmartSync' could not be found in project ':SalesforceHybrid'.
<a href="openFile:C:\test\SalesforceHybrid\build.gradle">Open File</a>

**Comment by wmathurin** [comment]
Make sure to install shelljs version 0.5.3
In your steps, use 
```
npm install shelljs@0.5.3
```
instead of 
```
npm install shelljs
```

**Comment by JavierAbrego** [comment]
Thanks Wolfgang it worked!

**Pull request merged**
