### PR TITLE
Upgrading to Cordova 4.5.4 for iOS

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by wmathurin** [comment]
(Duplicating comment I put on the commit)
SalesforceSDKManagerWithSmartStore.h was renamed to SmartStoreSDKManager.h. But you should not need it anymore since we use SalesforceHybridSDKManager in hybrid apps.

**Comment by wmathurin** [comment]
Also why are we still bringing in SFAuthenticationManager.h?

**Comment by wmathurin** [comment]
Then you probably need the whole chain:  SalesforceHybridSDKManager, SmartSyncSDKManager, SmartStoreSDKManager and SalesforceSDKCoreManager.h

**Comment by bhariharan** [comment]
Correct - we need the whole chain. As for `SFAuthenticationManager.h`, shouldn't it be available for backward compatibility?

**Comment by bhariharan** [comment]
Generated app works fine now. All set!

**Pull request merged**
