### PR TITLE
Latest from iOS source repo

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by wmathurin** [comment]
Looks fine. Apps are generated ok?

**Comment by wmathurin** [comment]
What version of cordova cli should I install to try it out?

**Comment by bhariharan** [comment]
I'm trying it now. Need to make a few tweaks to ```plugin.xml``` to include a couple more headers that we've added, but overall it's looking good so far. You'll need ```Cordova CLI 5.4.0``` to try it out.

**Comment by bhariharan** [comment]
Added missing headers [here](https://github.com/bhariharan/SalesforceMobileSDK-CordovaPlugin/commit/8f69e8eca65c3a6b68954a8cdd39e55d296e5d08).

**Comment by bhariharan** [comment]
@wmathurin Generated a ```hybrid_remote``` app and launched it in ```iOS 8.4``` simulator. Logged in and poked around. Works like a charm so far.

**Comment by bhariharan** [comment]
```hybrid_local``` works too. Merging.

**Comment by wmathurin** [comment]
Awesome

**Pull request merged**
